---
- name: lets go
  hosts: localhost
  become: false
  connection: local

  vars:
    motd_title: The bestest Mmhoo
    motd_alias: cn01
    motd_func: Ansible AAP Control node
    motd_location: Amsterdam
    motd_vmname: EXDTONKE01

  tasks:
    - name: get cowsay
      cowsay:
        text: "{{ motd_title }}"
      register: cowsaid
      delegate_to: localhost

    - name: do template
      template:
        src: motd.j2
        dest: /tmp/motd
